# htmltest configuration
# https://github.com/wjdp/htmltest

DirectoryPath: "public"

# Check internal links (anchors, relative paths)
CheckInternal: true

# Check external links
CheckExternal: true

# Don't fail on external link errors (sites may be temporarily down)
IgnoreExternalBrokenLinks: true

# Timeout for external link checks
ExternalTimeout: 15

# Ignore URLs matching these patterns
# In PR preview builds, Hugo generates internal links prefixed with
# /pr-preview/N/ (matching the baseURL override). These don't resolve
# against the local public/ directory, so we skip them here. Hugo
# validates internal links during build anyway.
IgnoreURLs:
  - "^mailto:"
  - "^/pr-preview/"

# Ignore PR preview directories (they reference other PR builds)
IgnoreDirs:
  - "^pr-preview/"

# Output format
OutputDir: ".htmltest"
