# htmltest configuration
# https://github.com/wjdp/htmltest

DirectoryPath: "public"

# Check internal links (anchors, relative paths)
CheckInternal: true

# Check external links
CheckExternal: true

# Don't fail on external link errors (sites may be temporarily down)
IgnoreExternalBrokenLinks: true

# Timeout for external link checks
ExternalTimeout: 15

# Ignore URLs matching these patterns
# Theme-generated assets use absolute URLs with baseURL prefix
# which htmltest can't resolve against the local public/ directory
IgnoreURLs:
  - "^mailto:"
  - "/urbanism-guide.*\\.(css|js|png|ico|json|svg|woff2?)$"
  - "/pr-preview/.*\\.(css|js|png|ico|json|svg|woff2?)$"
  - "^/urbanism-guide/(favicon|manifest|apple-touch)"
  - "^/urbanism-guide/pr-preview/\\d+/(favicon|manifest|apple-touch)"

# Ignore PR preview directories (they reference other PR builds)
IgnoreDirs:
  - "^pr-preview/"

# Output format
OutputDir: ".htmltest"
