# htmltest configuration
# https://github.com/wjdp/htmltest

DirectoryPath: "public"

# Check internal links (anchors, relative paths)
CheckInternal: true

# Skip external links (checked by scripts/check-external-links.py instead)
CheckExternal: false

# Ignore URLs matching these patterns
# Hugo generates all internal links with the full baseURL prefix
# (e.g., /urbanism-guide/pr-preview/1/glossary/), but htmltest checks
# against the local public/ directory where files are at /glossary/.
# Hugo validates internal links during build, so we skip them here
# and focus on validating external links.
IgnoreURLs:
  - "^mailto:"
  - "^/urbanism-guide/"

# Ignore PR preview directories (they reference other PR builds)
IgnoreDirs:
  - "^pr-preview/"

# Output format
OutputDir: ".htmltest"
